/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hska.microServiceWebShop.service.SanityService;

import hska.microServiceWebShop.models.Role;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

public interface RolesApi {

    @RequestMapping(value = "/roles",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity createRole(@RequestBody Role role);

    @RequestMapping(value = "/roles/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity deleteRole(@PathVariable("id") Long id);

    @RequestMapping(value = "/roles/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity getRoleById( @PathVariable("id") Long id);

    @RequestMapping(value = "/roles",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity getRoles(@RequestHeader(value="Text",defaultValue = "") String text,
                                        @RequestHeader(value="Level",defaultValue = "") Integer level);

}
