/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hska.microServiceWebShop.service.APIService;

import hska.microServiceWebShop.models.Category;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

public interface CategoriesApi{

    @RequestMapping(value = "/categories",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity addCategory(@RequestBody Category name);

    @RequestMapping(value = "/categories/{id}",
            produces = { "application/json" },
            method = RequestMethod.DELETE)
    ResponseEntity deleteCategory(@PathVariable("id") Long id);

    @RequestMapping(value = "/categories/{id}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity getCategory( @PathVariable("id") Long id);

    @RequestMapping(value = "/categories",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity queryCategories(@RequestHeader(value="Text",defaultValue = "") String text);

}

