/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hska.microServiceWebShop.service.APIService;

import hska.microServiceWebShop.models.Product;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

public interface ProductsApi {

    @RequestMapping(value = "/products",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity addProduct(@RequestBody Product product);

    @RequestMapping(value = "/products/{id}",
            produces = { "application/json" },
            method = RequestMethod.DELETE)
    ResponseEntity deleteProduct(
            @PathVariable("id") Long id);

    @RequestMapping(value = "/products/{id}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity getProduct(@PathVariable("id") Long id);

    @RequestMapping(value = "/products",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity queryProducts(@RequestHeader(value="Text",defaultValue = "") String text,
                                 @RequestHeader(value="Category",defaultValue = "") Long category,
                                 @RequestHeader(value="PriceMin",defaultValue = "") Double priceMin,
                                 @RequestHeader(value="PriceMax",defaultValue = "") Double priceMax);

}