version: '3'

services:
  discovery-service:
    image: discovery_service:latest
    network_mode: host
    ports:
      - "8761:8761"
  edge_service:
    image: edge_service:latest
    network_mode: host
    ports:
      - "8091:8091"
  category-service:
    image: category_service:latest
    network_mode: host
    ports:
      - "8083:8083"
  product-service:
    image: product_service:latest
    network_mode: host
    ports:
      - "8082:8082"
  user-role-service:
    image: user_role_service:latest
    network_mode: host
    ports:
      - "8086:8086"
  sanity-service:
    image: sanity_service:latest
    network_mode: host
    ports:
      - "8081:8081"
  api-service:
    image: api_service:latest
    network_mode: host
    ports:
      - "8085:8085"
  frontend:
    image: frontend:latest
    network_mode: host
    ports:
      - "4200:8080"
