/*
 * Sanity Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bhb127@outlook.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hska.microServiceWebShop.api;

import hska.microServiceWebShop.ApiException;
import hska.microServiceWebShop.models.Category;
import hska.microServiceWebShop.models.CategoryQuery;
import hska.microServiceWebShop.models.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    
    /**
     * Adds a new category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addCategoryTest() throws ApiException {
        Category name = new Category();
        name.setName("cat1");
        Category response = api.addCategory(name);
        assert response.getName() == "cat1";
        assert response.getId() != null;
    }
    
    /**
     * Deletes a category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCategoryTest() throws ApiException {
        Category name = new Category();
        name.setName("cat2");
        Category response = api.addCategory(name);
        Long id = response.getId();
        api.deleteCategory(id);
    }
    
    /**
     * Retrieves a category
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoryTest() throws ApiException {
        Category name = new Category();
        name.setName("cat3");
        Category response = api.addCategory(name);
        Long id = response.getId();
        Category response2 = api.getCategory(id);
        assert response2.getName() == "cat3";
        // TODO: test validations
    }
    
    /**
     * Queries categories. If no name is provided all categories will be returned
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryCategoriesTest() throws ApiException {
        CategoryQuery query = new CategoryQuery();
        List<Category> response = api.queryCategories(query);

        // TODO: test validations
    }
    
}
