/*
 * Sanity Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bhb127@outlook.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hska.microServiceWebShop.api;

import hska.microServiceWebShop.ApiException;
import hska.microServiceWebShop.models.Error;
import hska.microServiceWebShop.models.Product;
import hska.microServiceWebShop.models.ProductQuery;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Ignore
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    
    /**
     * Adds a new product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProductTest() throws ApiException {
        Product product = new Product();
        product.setName("Pro1");
        product.setCategory(1L);
        product.setPrice(50.5);
        try {
        Product response = api.addProduct(product);
        }catch (ApiException e){
            System.err.println(e.getCode());
            System.err.println(e.getMessage());
            System.err.println(e.getResponseBody());
            e.printStackTrace(System.err);
        }

        // TODO: test validations
    }
    
    /**
     * Deletes a product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProductTest() throws ApiException {
        Product product = new Product();
        product.setName("Pro2");
        product.setCategory(1L);
        product.setPrice(50.5);
        Product response = api.addProduct(product);
        Long id = response.getId();
        api.deleteProduct(id);

        // TODO: test validations
    }
    
    /**
     * Retrieves a product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductTest() throws ApiException {
        Product product = new Product();
        product.setName("Pro3");
        product.setCategory(1L);
        product.setPrice(50.5);
        Product response = api.addProduct(product);
        Long id = response.getId();
        Product response2 = api.getProduct(id);

        // TODO: test validations
    }
    
    /**
     * Queries products. If no parameters is provided all products will be returned
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryProductsTest() throws ApiException {
        ProductQuery query = new ProductQuery();
        List<Product> response = api.queryProducts(query);

        // TODO: test validations
    }
    
}
