/*
 * Sanity Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bhb127@outlook.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package hska.microServiceWebShop.api;

import hska.microServiceWebShop.ApiException;
import hska.microServiceWebShop.models.*;
import hska.microServiceWebShop.models.UserBackend;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for UserRoleApi
 */
@Ignore
public class UserRoleApiTest {

    private final UserRoleApi api = new UserRoleApi();

    
    /**
     * Create role
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRoleTest() throws ApiException {
        Role role = new Role();
        role.setTyp("role1");
        role.setLevel(1);

        System.out.println("create role");
        role = api.createRole(role);
        System.out.println(role.toString());

        System.out.println("get rolebyid");
        Long id = role.getId();
        Role response = api.getRoleById(id);
        
        System.out.println(response.toString());

        System.out.println("query roles");
        RoleQuery query = new RoleQuery();
        List<Role> responses = api.getRoles(query);
        
        for(Role r: responses) {
        	System.out.println(r.toString());
        }
        
        System.out.println("query role1");
        query = new RoleQuery();
        query.setText("role1");
        responses = api.getRoles(query);
        
        for(Role r: responses) {
        	System.out.println(r.toString());
        }
        // TODO: test validations
        
        System.out.println("delete role1");
        id = response.getId();
        api.deleteRole(id);
        
        System.out.println("try get role1");
        try {
        	api.getRoleById(id);
        	assert false;
        }catch(ApiException e) {
        	System.out.println(e.getMessage());
        }

        // TODO: test validations
    }
    
    @Test
    public void creatUserTest() throws ApiException {
        Role role = new Role();
        role.setTyp("role2");
        role.setLevel(1);

        System.out.println("create role2");
        role = api.createRole(role);
        System.out.println(role.toString());

        UserBackend userBackend = new UserBackend();
        userBackend.setFirstName("John");
        userBackend.setLastName("Doe");
        userBackend.setPassword("1234");
        userBackend.setRoleID(role.getId());
        userBackend.setUsername("UserBackend");
        
        System.out.println("create userBackend");
        User user = api.createUser(userBackend);
        System.out.println(userBackend.toString());
        
        System.out.println("get userbyid");
        Long id = userBackend.getId();
        User response = api.getUserById(id);
        
        System.out.println(response.toString());

        System.out.println("query users");
        UserQuery query = new UserQuery();
        List<User> responses = api.getUsers(query);
        
        for(User r: responses) {
        	System.out.println(r.toString());
        }
        
        System.out.println("query user1");
        query = new UserQuery();
        query.setText("UserBackend");
        responses = api.getUsers(query);
        
        for(User r: responses) {
        	System.out.println(r.toString());
        }
        // TODO: test validations
        
        System.out.println("delete user1");
        id = response.getId();
        api.deleteUser(id);
        
        System.out.println("delete role1");
        id = role.getId();
        api.deleteRole(id);
        
        System.out.println("try get user1");
        try {
        	api.getUserById(id);
        	assert false;
        }catch(ApiException e) {
        	System.out.println(e.getMessage());
        }

        // TODO: test validations
    }
    
}
